/**
 * Converter registry for Conversion Tools n8n node
 * Maps conversion types to human-readable names
 */

export interface ConverterInfo {
	type: string;
	name: string;
	description: string;
	inputFormats: string[];
	outputFormat: string;
	category: string;
}

export const CONVERTERS: ConverterInfo[] = [
	// Data Format Converters
	{
		type: 'convert.json_to_csv',
		name: 'JSON to CSV',
		description: 'Convert JSON to CSV',
		inputFormats: ['json'],
		outputFormat: 'csv',
		category: 'data',
	},
	{
		type: 'convert.json_to_excel',
		name: 'JSON to Excel',
		description: 'Convert JSON to Excel spreadsheet',
		inputFormats: ['json'],
		outputFormat: 'xlsx',
		category: 'data',
	},
	{
		type: 'convert.json_to_xml',
		name: 'JSON to XML',
		description: 'Convert JSON to XML',
		inputFormats: ['json'],
		outputFormat: 'xml',
		category: 'data',
	},
	{
		type: 'convert.csv_to_json',
		name: 'CSV to JSON',
		description: 'Convert CSV to JSON array',
		inputFormats: ['csv'],
		outputFormat: 'json',
		category: 'data',
	},
	{
		type: 'convert.csv_to_xml',
		name: 'CSV to XML',
		description: 'Convert CSV to XML',
		inputFormats: ['csv'],
		outputFormat: 'xml',
		category: 'data',
	},
	{
		type: 'convert.csv_to_excel',
		name: 'CSV to Excel',
		description: 'Convert CSV to Excel',
		inputFormats: ['csv'],
		outputFormat: 'xlsx',
		category: 'data',
	},
	{
		type: 'convert.xml_to_json',
		name: 'XML to JSON',
		description: 'Convert XML to JSON',
		inputFormats: ['xml'],
		outputFormat: 'json',
		category: 'data',
	},
	{
		type: 'convert.xml_to_csv',
		name: 'XML to CSV',
		description: 'Convert XML to CSV',
		inputFormats: ['xml'],
		outputFormat: 'csv',
		category: 'data',
	},
	{
		type: 'convert.xml_to_excel',
		name: 'XML to Excel',
		description: 'Convert XML to Excel',
		inputFormats: ['xml'],
		outputFormat: 'xlsx',
		category: 'data',
	},
	{
		type: 'convert.excel_to_json',
		name: 'Excel to JSON',
		description: 'Convert Excel to JSON',
		inputFormats: ['xlsx', 'xls'],
		outputFormat: 'json',
		category: 'data',
	},
	{
		type: 'convert.excel_to_csv',
		name: 'Excel to CSV',
		description: 'Convert spreadsheets to CSV',
		inputFormats: ['xlsx', 'xls'],
		outputFormat: 'csv',
		category: 'data',
	},
	{
		type: 'convert.excel_to_xml',
		name: 'Excel to XML',
		description: 'Convert Excel to XML',
		inputFormats: ['xlsx', 'xls'],
		outputFormat: 'xml',
		category: 'data',
	},

	// PDF Converters
	{
		type: 'convert.pdf_to_word',
		name: 'PDF to Word',
		description: 'Convert PDF to editable Word document',
		inputFormats: ['pdf'],
		outputFormat: 'docx',
		category: 'pdf',
	},
	{
		type: 'convert.pdf_to_excel',
		name: 'PDF to Excel',
		description: 'Extract tables from PDF to Excel',
		inputFormats: ['pdf'],
		outputFormat: 'xlsx',
		category: 'pdf',
	},
	{
		type: 'convert.pdf_to_csv',
		name: 'PDF to CSV',
		description: 'Extract tables from PDF to CSV',
		inputFormats: ['pdf'],
		outputFormat: 'csv',
		category: 'pdf',
	},
	{
		type: 'convert.pdf_to_text',
		name: 'PDF to Text',
		description: 'Extract text from PDF',
		inputFormats: ['pdf'],
		outputFormat: 'txt',
		category: 'pdf',
	},
	{
		type: 'convert.pdf_to_jpg',
		name: 'PDF to JPG',
		description: 'Convert PDF pages to JPG images',
		inputFormats: ['pdf'],
		outputFormat: 'jpg',
		category: 'pdf',
	},
	{
		type: 'convert.pdf_to_png',
		name: 'PDF to PNG',
		description: 'Convert PDF pages to PNG images',
		inputFormats: ['pdf'],
		outputFormat: 'png',
		category: 'pdf',
	},

	// Document Converters
	{
		type: 'convert.word_to_pdf',
		name: 'Word to PDF',
		description: 'Convert Word documents to PDF',
		inputFormats: ['docx', 'doc'],
		outputFormat: 'pdf',
		category: 'documents',
	},
	{
		type: 'convert.word_to_text',
		name: 'Word to Text',
		description: 'Extract text from Word documents',
		inputFormats: ['docx', 'doc'],
		outputFormat: 'txt',
		category: 'documents',
	},
	{
		type: 'convert.powerpoint_to_pdf',
		name: 'PowerPoint to PDF',
		description: 'Convert presentations to PDF',
		inputFormats: ['pptx', 'ppt'],
		outputFormat: 'pdf',
		category: 'documents',
	},
	{
		type: 'convert.excel_to_pdf',
		name: 'Excel to PDF',
		description: 'Convert spreadsheets to PDF',
		inputFormats: ['xlsx', 'xls'],
		outputFormat: 'pdf',
		category: 'documents',
	},
	{
		type: 'convert.markdown_to_pdf',
		name: 'Markdown to PDF',
		description: 'Convert Markdown to PDF',
		inputFormats: ['md'],
		outputFormat: 'pdf',
		category: 'documents',
	},
	{
		type: 'convert.markdown_to_html',
		name: 'Markdown to HTML',
		description: 'Convert Markdown to HTML',
		inputFormats: ['md'],
		outputFormat: 'html',
		category: 'documents',
	},

	// Image Converters
	{
		type: 'convert.png_to_jpg',
		name: 'PNG to JPG',
		description: 'Convert PNG to JPG',
		inputFormats: ['png'],
		outputFormat: 'jpg',
		category: 'images',
	},
	{
		type: 'convert.jpg_to_png',
		name: 'JPG to PNG',
		description: 'Convert JPG to PNG',
		inputFormats: ['jpg', 'jpeg'],
		outputFormat: 'png',
		category: 'images',
	},
	{
		type: 'convert.png_to_webp',
		name: 'PNG to WebP',
		description: 'Convert PNG to WebP',
		inputFormats: ['png'],
		outputFormat: 'webp',
		category: 'images',
	},
	{
		type: 'convert.jpg_to_webp',
		name: 'JPG to WebP',
		description: 'Convert JPG to WebP',
		inputFormats: ['jpg', 'jpeg'],
		outputFormat: 'webp',
		category: 'images',
	},
	{
		type: 'convert.heic_to_jpg',
		name: 'HEIC to JPG',
		description: 'Convert iPhone HEIC to JPG',
		inputFormats: ['heic'],
		outputFormat: 'jpg',
		category: 'images',
	},
	{
		type: 'convert.jpg_to_pdf',
		name: 'JPG to PDF',
		description: 'Convert JPG images to PDF',
		inputFormats: ['jpg', 'jpeg'],
		outputFormat: 'pdf',
		category: 'images',
	},
	{
		type: 'convert.png_to_pdf',
		name: 'PNG to PDF',
		description: 'Convert PNG images to PDF',
		inputFormats: ['png'],
		outputFormat: 'pdf',
		category: 'images',
	},

	// OCR Converters
	{
		type: 'convert.ocr_pdf_to_text',
		name: 'OCR PDF to Text',
		description: 'Extract text from scanned PDF using OCR',
		inputFormats: ['pdf'],
		outputFormat: 'txt',
		category: 'ocr',
	},
	{
		type: 'convert.ocr_jpg_to_text',
		name: 'OCR JPG to Text',
		description: 'Extract text from JPG using OCR',
		inputFormats: ['jpg', 'jpeg'],
		outputFormat: 'txt',
		category: 'ocr',
	},
	{
		type: 'convert.ocr_png_to_text',
		name: 'OCR PNG to Text',
		description: 'Extract text from PNG using OCR',
		inputFormats: ['png'],
		outputFormat: 'txt',
		category: 'ocr',
	},

	// Web/URL Converters
	{
		type: 'convert.website_to_pdf',
		name: 'Website to PDF',
		description: 'Capture website as PDF',
		inputFormats: ['url'],
		outputFormat: 'pdf',
		category: 'web',
	},
	{
		type: 'convert.website_to_jpg',
		name: 'Website to JPG',
		description: 'Screenshot website as JPG',
		inputFormats: ['url'],
		outputFormat: 'jpg',
		category: 'web',
	},
	{
		type: 'convert.website_to_png',
		name: 'Website to PNG',
		description: 'Screenshot website as PNG',
		inputFormats: ['url'],
		outputFormat: 'png',
		category: 'web',
	},
	{
		type: 'convert.html_table_to_csv',
		name: 'HTML Table to CSV',
		description: 'Extract HTML tables to CSV',
		inputFormats: ['html'],
		outputFormat: 'csv',
		category: 'web',
	},

	// Audio/Video Converters
	{
		type: 'convert.mp4_to_mp3',
		name: 'MP4 to MP3',
		description: 'Extract audio from video',
		inputFormats: ['mp4'],
		outputFormat: 'mp3',
		category: 'audio',
	},
	{
		type: 'convert.wav_to_mp3',
		name: 'WAV to MP3',
		description: 'Convert WAV to MP3',
		inputFormats: ['wav'],
		outputFormat: 'mp3',
		category: 'audio',
	},
	{
		type: 'convert.mov_to_mp4',
		name: 'MOV to MP4',
		description: 'Convert MOV to MP4',
		inputFormats: ['mov'],
		outputFormat: 'mp4',
		category: 'video',
	},
	{
		type: 'convert.mkv_to_mp4',
		name: 'MKV to MP4',
		description: 'Convert MKV to MP4',
		inputFormats: ['mkv'],
		outputFormat: 'mp4',
		category: 'video',
	},

	// Subtitle Converters
	{
		type: 'convert.srt_to_vtt',
		name: 'SRT to VTT',
		description: 'Convert SRT to WebVTT',
		inputFormats: ['srt'],
		outputFormat: 'vtt',
		category: 'subtitles',
	},
	{
		type: 'convert.vtt_to_srt',
		name: 'VTT to SRT',
		description: 'Convert WebVTT to SRT',
		inputFormats: ['vtt'],
		outputFormat: 'srt',
		category: 'subtitles',
	},
	{
		type: 'convert.srt_to_text',
		name: 'SRT to Text',
		description: 'Extract text from subtitles',
		inputFormats: ['srt'],
		outputFormat: 'txt',
		category: 'subtitles',
	},
];
